


[workspace]
members = [
    "mora-core",
    "mora-queue",
    "mora-api",
    "mora-server",
    "mora-client",
    "mora-cli",
]

[workspace.dependencies]
log = "0.4.17"
mora-core = {path = "./mora-core"}
mora-queue = {path = "./mora-queue"}
mora-api = {path = "./mora-api"}
mora-server = {path = "./mora-server"}
mora-client = {path = "./mora-client"}
mora-cli = {path = "./mora-cli"}
