
[workspace]
resolver = "2"
members = [
    "mora-core",
    "mora-queue",
    "mora-api",
    "mora-server",
    "mora-client",
    "mora-cli",
]

[workspace.dependencies]
mora-core = { path = "./mora-core" }
mora-channel = { path = "./mora-channel" }
mora-queue = { path = "./mora-queue" }
mora-api = { path = "./mora-api" }
mora-server = { path = "./mora-server" }
mora-client = { path = "./mora-client" }
mora-cli = { path = "./mora-cli" }

axum = { version = "0.8.1" }
axum-macros = { version = "0.5.0" }
config = { version = "0.15.11" }
log = "0.4.17"
serde = { version = "1.0.163", features = ["derive"] }
simple_logger = "5.0.0"
regex = { version = "1.8.1" }
tokio = { version = "1.28.1", features = ["full"] }
thiserror = { version = "2.0.12" }
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "macro-diagnostics"] }
