version: "3.9"
services:
  mora:
    build:
      context: .
      args:
        MIX_ENV: "${MIX_ENV}"
        RELEASE_ENV: "${RELEASE_ENV}"
    image: edoardocostantinidev/mora
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: "${MIX_ENV}"
      RELEASE_ENV: "${RELEASE_ENV}"
      PORT: "4000"