[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.watch-dev]
dependencies = ["fmt", "clippy", "test"]

[tasks.watch-api]
env = { MORA_CHANNEL_TIMEOUT_IN_MSEC = 1000 }
workspace = false
script = "./watch_api.sh"
watch = true

[tasks.run-server]
workspace = false
cwd = "mora-server"
command = "cargo"
args = ["run"]
watch = true


[tasks.api-tests]
cwd = "k6"
workspace = false
command = "k6"
args = ["run", "--quiet", "api.js"]

[tasks.wtest]
command = "cargo"
args = ["test"]
watch = true

[tasks.wclippy]
command = "cargo"
args = ["clippy"]
watch = true

[tasks.wcheck]
command = "cargo"
args = ["check"]
watch = true

[tasks.wbuild]
command = "cargo"
args = ["build"]
watch = true

[tasks.wrun]
command = "cargo"
args = ["run"]
watch = true
