---
kind: Namespace
apiVersion: v1
metadata:
  name: mora

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mora
  namespace: mora
  labels:
    app.kubernetes.io/name: mora
    app.kubernetes.io/instance: mora-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mora
      app.kubernetes.io/instance: mora-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mora
        app.kubernetes.io/instance: mora-node
    spec:
      containers:
        - name: main
          image: edgardking/mora:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
          env:
            - name: RELEASE_DISTRIBUTION
              value: "name"
            - name: PORT
              value: "4000"
            - name: RELEASE_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_NODE
              value: "mora@$(RELEASE_NODE_IP)"
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: mora-cluster
                  key: ERLANG_COOKIE
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP
            - name: http
              containerPort: 4000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mora-svc-headless
  namespace: mora
  labels:
    app.kubernetes.io/name: mora
    app.kubernetes.io/instance: mora-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app.kubernetes.io/name: mora
    app.kubernetes.io/instance: mora-node

---
kind: Service
apiVersion: v1

metadata:
  name: mora-svc-api
  namespace: mora
  labels:
    app.kubernetes.io/name: mora
    app.kubernetes.io/instance: mora-svc-api
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mora
    app.kubernetes.io/instance: mora-node
  ports:
    - port: 8000
      targetPort: 4000
