[package]
name = "mora-server"
version = "0.1.0"
edition = "2021"
default-run = "mora-server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.2"
serde = "1.0.143"
serde_derive = "1.0.143"
mora-core = { workspace = true }
mora-api = { workspace = true }
