[package]
name = "mora-server"
version = "0.1.0"
edition = "2021"
default-run = "mora-server"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.2"
log = { workspace = true }
mora-api = { workspace = true }
mora-channel = { workspace = true }
mora-core = { workspace = true }
mora-queue = { workspace = true }
serde = { workspace = true }
simple_logger = { workspace = true }
tokio = { workspace = true }
